export const GET_ALL_LEAVE_REQUESTS_REQUEST = "GET_ALL_LEAVE_REQUESTS_REQUEST";
export const GET_ALL_LEAVE_REQUESTS_SUCCESS = "GET_ALL_LEAVE_REQUESTS_SUCCESS";
export const GET_ALL_LEAVE_REQUESTS_FAIL = "GET_ALL_LEAVE_REQUESTS_FAIL";
export const GET_ALL_LEAVE_REQUESTS_RESET = "GET_ALL_LEAVE_REQUESTS_RESET";

export const GET_LIST_LEAVE_REQUESTS_REQUEST =
  "GET_LIST_LEAVE_REQUESTS_REQUEST";
export const GET_LIST_LEAVE_REQUESTS_SUCCESS =
  "GET_LIST_LEAVE_REQUESTS_SUCCESS";
export const GET_LIST_LEAVE_REQUESTS_FAIL = "GET_LIST_LEAVE_REQUESTS_FAIL";
export const GET_LIST_LEAVE_REQUESTS_RESET = "GET_LIST_LEAVE_REQUESTS_RESET";

export const GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_REQUEST =
  "GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_REQUEST";
export const GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_SUCCESS =
  "GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_SUCCESS";
export const GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_FAIL =
  "GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_FAIL";
export const GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_RESET =
  "GET_SINGLE_TO_CREATE_LEAVE_REQUESTS_RESET";

export const GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_REQUEST =
  "GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_REQUEST";
export const GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_SUCCESS =
  "GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_SUCCESS";
export const GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_FAIL =
  "GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_FAIL";
export const GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_RESET =
  "GET_SINGLE_TO_EDIT_LEAVE_REQUESTS_RESET";

export const POST_LEAVE_REQUESTS_REQUEST = "POST_LEAVE_REQUESTS_REQUEST";
export const POST_LEAVE_REQUESTS_SUCCESS = "POST_LEAVE_REQUESTS_SUCCESS";
export const POST_LEAVE_REQUESTS_FAIL = "POST_LEAVE_REQUESTS_FAIL";
export const POST_LEAVE_REQUESTS_RESET = "POST_LEAVE_REQUESTS_RESET";

export const PUT_LEAVE_REQUESTS_REQUEST = "PUT_LEAVE_REQUESTS_REQUEST";
export const PUT_LEAVE_REQUESTS_SUCCESS = "PUT_LEAVE_REQUESTS_SUCCESS";
export const PUT_LEAVE_REQUESTS_FAIL = "PUT_LEAVE_REQUESTS_FAIL";
export const PUT_LEAVE_REQUESTS_RESET = "PUT_LEAVE_REQUESTS_RESET";

export const GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_REQUEST =
  "GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_REQUEST";
export const GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_SUCCESS =
  "GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_SUCCESS";
export const GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_FAIL =
  "GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_FAIL";
export const GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_RESET =
  "GET_SINGLE_TO_DELETE_LEAVE_REQUESTS_RESET";

export const DELETE_LEAVE_REQUESTS_REQUEST = "DELETE_LEAVE_REQUESTS_REQUEST";
export const DELETE_LEAVE_REQUESTS_SUCCESS = "DELETE_LEAVE_REQUESTS_SUCCESS";
export const DELETE_LEAVE_REQUESTS_FAIL = "DELETE_LEAVE_REQUESTS_FAIL";
export const DELETE_LEAVE_REQUESTS_RESET = "DELETE_LEAVE_REQUESTS_RESET";

export const DOWNLOAD_DOC_LEAVE_REQUESTS_REQUEST =
  "DOWNLOAD_DOC_LEAVE_REQUESTS_REQUEST";
export const DOWNLOAD_DOC_LEAVE_REQUESTS_SUCCESS =
  "DOWNLOAD_DOC_LEAVE_REQUESTS_SUCCESS";
export const DOWNLOAD_DOC_LEAVE_REQUESTS_FAIL =
  "DOWNLOAD_DOC_LEAVE_REQUESTS_FAIL";
export const DOWNLOAD_DOC_LEAVE_REQUESTS_RESET =
  "DOWNLOAD_DOC_LEAVE_REQUESTS_RESET";

export const GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_REQUEST =
  "GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_REQUEST";
export const GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_SUCCESS =
  "GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_SUCCESS";
export const GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_FAIL =
  "GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_FAIL";
export const GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_RESET =
  "GET_SINGLE_TO_EDIT_SENT_LEAVE_REQUESTS_RESET";
