export const GET_TEACHER_DASHBOARD_REQUEST = "GET_TEACHER_DASHBOARD_REQUEST";
export const GET_TEACHER_DASHBOARD_SUCCESS = "GET_TEACHER_DASHBOARD_SUCCESS";
export const GET_TEACHER_DASHBOARD_FAIL = "GET_TEACHER_DASHBOARD_FAIL";
export const GET_TEACHER_DASHBOARD_RESET = "GET_TEACHER_DASHBOARD_RESET";
