export const GET_ALL_HOLIDAY_REQUEST = "GET_ALL_HOLIDAY_REQUEST";
export const GET_ALL_HOLIDAY_SUCCESS = "GET_ALL_HOLIDAY_SUCCESS";
export const GET_ALL_HOLIDAY_FAIL = "GET_ALL_HOLIDAY_FAIL";
export const GET_ALL_HOLIDAY_RESET = "GET_ALL_HOLIDAY_RESET";
