export const GET_ALL_ANNOUNCEMENT_TEACHER_REQUEST = "GET_ALL_ANNOUNCEMENT_TEACHER_REQUEST";
export const GET_ALL_ANNOUNCEMENT_TEACHER_SUCCESS = "GET_ALL_ANNOUNCEMENT_TEACHER_SUCCESS";
export const GET_ALL_ANNOUNCEMENT_TEACHER_FAIL = "GET_ALL_ANNOUNCEMENT_TEACHER_FAIL";
export const GET_ALL_ANNOUNCEMENT_TEACHER_RESET = "GET_ALL_ANNOUNCEMENT_TEACHER_RESET";

export const GET_LIST_ANNOUNCEMENT_TEACHER_REQUEST = "GET_LIST_ANNOUNCEMENT_TEACHER_REQUEST";
export const GET_LIST_ANNOUNCEMENT_TEACHER_SUCCESS = "GET_LIST_ANNOUNCEMENT_TEACHER_SUCCESS";
export const GET_LIST_ANNOUNCEMENT_TEACHER_FAIL = "GET_LIST_ANNOUNCEMENT_TEACHER_FAIL";
export const GET_LIST_ANNOUNCEMENT_TEACHER_RESET = "GET_LIST_ANNOUNCEMENT_TEACHER_RESET";

export const ANNOUNCEMENT_TEACHER_FCM_REQUEST = "ANNOUNCEMENT_TEACHER_FCM_REQUEST";
export const ANNOUNCEMENT_TEACHER_FCM_SUCCESS = "ANNOUNCEMENT_TEACHER_FCM_SUCCESS";
export const ANNOUNCEMENT_TEACHER_FCM_FAIL = "ANNOUNCEMENT_TEACHER_FCM_FAIL";
export const ANNOUNCEMENT_TEACHER_FCM_RESET = "ANNOUNCEMENT_TEACHER_FCM_RESET";